import { Navbar } from "@/components/navbar";
import "./globals.css";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Coach report",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <section className="p-2">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
